//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consumo.ServiceControlProteina {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://uca.edu.org/")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private int GoalField;
        
        private int TotalField;
        
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Goal {
            get {
                return this.GoalField;
            }
            set {
                if ((this.GoalField.Equals(value) != true)) {
                    this.GoalField = value;
                    this.RaisePropertyChanged("Goal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://uca.edu.org/", ConfigurationName="ServiceControlProteina.GrettingSoap")]
    public interface GrettingSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://uca.edu.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://uca.edu.org/HelloWorld", ReplyAction="*")]
        Consumo.ServiceControlProteina.HelloWorldResponse HelloWorld(Consumo.ServiceControlProteina.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://uca.edu.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Consumo.ServiceControlProteina.HelloWorldResponse> HelloWorldAsync(Consumo.ServiceControlProteina.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://uca.edu.org/AddProteint", ReplyAction="*")]
        int AddProteint(int amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://uca.edu.org/AddProteint", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddProteintAsync(int amount);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento name del espacio de nombres http://uca.edu.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://uca.edu.org/AddUser", ReplyAction="*")]
        Consumo.ServiceControlProteina.AddUserResponse AddUser(Consumo.ServiceControlProteina.AddUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://uca.edu.org/AddUser", ReplyAction="*")]
        System.Threading.Tasks.Task<Consumo.ServiceControlProteina.AddUserResponse> AddUserAsync(Consumo.ServiceControlProteina.AddUserRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento listuserResult del espacio de nombres http://uca.edu.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://uca.edu.org/listuser", ReplyAction="*")]
        Consumo.ServiceControlProteina.listuserResponse listuser(Consumo.ServiceControlProteina.listuserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://uca.edu.org/listuser", ReplyAction="*")]
        System.Threading.Tasks.Task<Consumo.ServiceControlProteina.listuserResponse> listuserAsync(Consumo.ServiceControlProteina.listuserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://uca.edu.org/AddProtein", ReplyAction="*")]
        int AddProtein(int amoun, int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://uca.edu.org/AddProtein", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddProteinAsync(int amoun, int ID);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://uca.edu.org/", Order=0)]
        public Consumo.ServiceControlProteina.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Consumo.ServiceControlProteina.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://uca.edu.org/", Order=0)]
        public Consumo.ServiceControlProteina.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Consumo.ServiceControlProteina.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://uca.edu.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddUser", Namespace="http://uca.edu.org/", Order=0)]
        public Consumo.ServiceControlProteina.AddUserRequestBody Body;
        
        public AddUserRequest() {
        }
        
        public AddUserRequest(Consumo.ServiceControlProteina.AddUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://uca.edu.org/")]
    public partial class AddUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int goal;
        
        public AddUserRequestBody() {
        }
        
        public AddUserRequestBody(string name, int goal) {
            this.name = name;
            this.goal = goal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddUserResponse", Namespace="http://uca.edu.org/", Order=0)]
        public Consumo.ServiceControlProteina.AddUserResponseBody Body;
        
        public AddUserResponse() {
        }
        
        public AddUserResponse(Consumo.ServiceControlProteina.AddUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://uca.edu.org/")]
    public partial class AddUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddUserResult;
        
        public AddUserResponseBody() {
        }
        
        public AddUserResponseBody(int AddUserResult) {
            this.AddUserResult = AddUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listuserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listuser", Namespace="http://uca.edu.org/", Order=0)]
        public Consumo.ServiceControlProteina.listuserRequestBody Body;
        
        public listuserRequest() {
        }
        
        public listuserRequest(Consumo.ServiceControlProteina.listuserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class listuserRequestBody {
        
        public listuserRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listuserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listuserResponse", Namespace="http://uca.edu.org/", Order=0)]
        public Consumo.ServiceControlProteina.listuserResponseBody Body;
        
        public listuserResponse() {
        }
        
        public listuserResponse(Consumo.ServiceControlProteina.listuserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://uca.edu.org/")]
    public partial class listuserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Consumo.ServiceControlProteina.User[] listuserResult;
        
        public listuserResponseBody() {
        }
        
        public listuserResponseBody(Consumo.ServiceControlProteina.User[] listuserResult) {
            this.listuserResult = listuserResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GrettingSoapChannel : Consumo.ServiceControlProteina.GrettingSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GrettingSoapClient : System.ServiceModel.ClientBase<Consumo.ServiceControlProteina.GrettingSoap>, Consumo.ServiceControlProteina.GrettingSoap {
        
        public GrettingSoapClient() {
        }
        
        public GrettingSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GrettingSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GrettingSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GrettingSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Consumo.ServiceControlProteina.HelloWorldResponse Consumo.ServiceControlProteina.GrettingSoap.HelloWorld(Consumo.ServiceControlProteina.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Consumo.ServiceControlProteina.HelloWorldRequest inValue = new Consumo.ServiceControlProteina.HelloWorldRequest();
            inValue.Body = new Consumo.ServiceControlProteina.HelloWorldRequestBody();
            Consumo.ServiceControlProteina.HelloWorldResponse retVal = ((Consumo.ServiceControlProteina.GrettingSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Consumo.ServiceControlProteina.HelloWorldResponse> Consumo.ServiceControlProteina.GrettingSoap.HelloWorldAsync(Consumo.ServiceControlProteina.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Consumo.ServiceControlProteina.HelloWorldResponse> HelloWorldAsync() {
            Consumo.ServiceControlProteina.HelloWorldRequest inValue = new Consumo.ServiceControlProteina.HelloWorldRequest();
            inValue.Body = new Consumo.ServiceControlProteina.HelloWorldRequestBody();
            return ((Consumo.ServiceControlProteina.GrettingSoap)(this)).HelloWorldAsync(inValue);
        }
        
        public int AddProteint(int amount) {
            return base.Channel.AddProteint(amount);
        }
        
        public System.Threading.Tasks.Task<int> AddProteintAsync(int amount) {
            return base.Channel.AddProteintAsync(amount);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Consumo.ServiceControlProteina.AddUserResponse Consumo.ServiceControlProteina.GrettingSoap.AddUser(Consumo.ServiceControlProteina.AddUserRequest request) {
            return base.Channel.AddUser(request);
        }
        
        public int AddUser(string name, int goal) {
            Consumo.ServiceControlProteina.AddUserRequest inValue = new Consumo.ServiceControlProteina.AddUserRequest();
            inValue.Body = new Consumo.ServiceControlProteina.AddUserRequestBody();
            inValue.Body.name = name;
            inValue.Body.goal = goal;
            Consumo.ServiceControlProteina.AddUserResponse retVal = ((Consumo.ServiceControlProteina.GrettingSoap)(this)).AddUser(inValue);
            return retVal.Body.AddUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Consumo.ServiceControlProteina.AddUserResponse> Consumo.ServiceControlProteina.GrettingSoap.AddUserAsync(Consumo.ServiceControlProteina.AddUserRequest request) {
            return base.Channel.AddUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<Consumo.ServiceControlProteina.AddUserResponse> AddUserAsync(string name, int goal) {
            Consumo.ServiceControlProteina.AddUserRequest inValue = new Consumo.ServiceControlProteina.AddUserRequest();
            inValue.Body = new Consumo.ServiceControlProteina.AddUserRequestBody();
            inValue.Body.name = name;
            inValue.Body.goal = goal;
            return ((Consumo.ServiceControlProteina.GrettingSoap)(this)).AddUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Consumo.ServiceControlProteina.listuserResponse Consumo.ServiceControlProteina.GrettingSoap.listuser(Consumo.ServiceControlProteina.listuserRequest request) {
            return base.Channel.listuser(request);
        }
        
        public Consumo.ServiceControlProteina.User[] listuser() {
            Consumo.ServiceControlProteina.listuserRequest inValue = new Consumo.ServiceControlProteina.listuserRequest();
            inValue.Body = new Consumo.ServiceControlProteina.listuserRequestBody();
            Consumo.ServiceControlProteina.listuserResponse retVal = ((Consumo.ServiceControlProteina.GrettingSoap)(this)).listuser(inValue);
            return retVal.Body.listuserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Consumo.ServiceControlProteina.listuserResponse> Consumo.ServiceControlProteina.GrettingSoap.listuserAsync(Consumo.ServiceControlProteina.listuserRequest request) {
            return base.Channel.listuserAsync(request);
        }
        
        public System.Threading.Tasks.Task<Consumo.ServiceControlProteina.listuserResponse> listuserAsync() {
            Consumo.ServiceControlProteina.listuserRequest inValue = new Consumo.ServiceControlProteina.listuserRequest();
            inValue.Body = new Consumo.ServiceControlProteina.listuserRequestBody();
            return ((Consumo.ServiceControlProteina.GrettingSoap)(this)).listuserAsync(inValue);
        }
        
        public int AddProtein(int amoun, int ID) {
            return base.Channel.AddProtein(amoun, ID);
        }
        
        public System.Threading.Tasks.Task<int> AddProteinAsync(int amoun, int ID) {
            return base.Channel.AddProteinAsync(amoun, ID);
        }
    }
}
